name: Deploy Static Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to GitHub Pages
      run: |
        echo "Deploying..."
        # Use your secret here
        echo "Your API key is ${{ secrets.API_KEY }}"
      env:
        API_KEY: ${{ secrets.API_KEY }}
